### ISSUE TITLE
Project Status and inactive email

### ISSUE THREAD

**Issue by suryaanshah** [google/mathsteps#265]
Hello! I am a user of Socratic app and a coder. This app has helped me a lot and so I thought of contributing to this amazing project.
I read the Contribution.md and found this email: mathsteps@socratic.org . I looked up some open issues, and found that multiple issues are now already resolved but are still open. I was confused if I was looking in the right repo and so I thought to email you but I found this email is inactive.
![image](https://user-images.githubusercontent.com/47082682/120911459-471e3e80-c6a5-11eb-86dc-072160d77ff1.png)

Please tell me if this project is still active and if this is the correct repo or way to contribute to the amazing work you are doing.
Thanks!

**Comment by evykassirer** [comment]
hi! i worked on this project as an intern in 2016, and since then socratic was acquired by google and then... I think they rewrote it and stopped using this code? not sure what the state of this repo is, but I haven't seen anyone maintain it for a while.

**Comment by suryaanshah** [comment]
Thanks for your response @evykassirer !
